Rails:
  Enabled: true
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Style/WordArray:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
