language: ruby
cache: bundler
rvm:
  - 2.2.5
  - 2.3.1
before_script:
  - psql -c 'create database enju_library_dummy_test;' -U postgres
  - bundle exec rake db:migrate
services:
  - redis-server
env:
  - DB=postgresql
notifications:
  slack:
    secure: RiboVJ5+DiKFZVN4kKnSvVmbd3An1/yiHN/PENUWLCo5PNF4ZnDAcd/V/uyawiblXNcINfX7XAN32RjtCVWDNvpNcF/RAynoltg6yc15GA4Io6tGRBNxtDe6qodvFWSsSw4Wzl2eS580vXMihWvB7Rghrt3dC+ub/SP1DkfZnq8=
sudo: false
addons:
  postgresql: "9.4"
  code_climate:
    repo_token: d0b171c39cff01a0f9d757a66524d3ad7f7867812e2e8a58e994829ac4adf4ce
